<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>Emploi du temps</title>
  <link rel="stylesheet" href="planning.css">
</head>
<body>
  <table class="emploi-du-temps">
    <thead>
      <tr>
        <th></th>
        <th>Lundi</th>
        <th>Mardi</th>
        <th>Mercredi</th>
        <th>Jeudi</th>
        <th>Vendredi</th>
      </tr>
    </thead>
    <tbody>
      <!-- Créez une ligne pour chaque heure de 8h à 18h -->
      <tr>
        <th>8h-9h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <th>9h-10h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <th>10h-11h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
	  <tr>
        <th>11h-12h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
	  <tr>
        <th>13h-14h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
	  <tr>
        <th>14h-15h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
	  <tr>
        <th>15h-16h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
	  <tr>
        <th>16h-17h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
	  <tr>
        <th>17h-18h</th>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
	  
    </tbody>
  </table>
</body>
</html>
